package com.lsheep.config.database.mapper;

import com.lsheep.config.database.model.SProperty;
import com.lsheep.config.database.model.SPropertyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SPropertyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_PROPERTY
	 * @mbg.generated
	 */
	long countByExample(SPropertyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_PROPERTY
	 * @mbg.generated
	 */
	int deleteByExample(SPropertyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_PROPERTY
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer propertyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_PROPERTY
	 * @mbg.generated
	 */
	int insert(SProperty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_PROPERTY
	 * @mbg.generated
	 */
	int insertSelective(SProperty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_PROPERTY
	 * @mbg.generated
	 */
	List<SProperty> selectByExampleWithBLOBs(SPropertyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_PROPERTY
	 * @mbg.generated
	 */
	List<SProperty> selectByExample(SPropertyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_PROPERTY
	 * @mbg.generated
	 */
	SProperty selectByPrimaryKey(Integer propertyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_PROPERTY
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") SProperty record, @Param("example") SPropertyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_PROPERTY
	 * @mbg.generated
	 */
	int updateByExampleWithBLOBs(@Param("record") SProperty record, @Param("example") SPropertyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_PROPERTY
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") SProperty record, @Param("example") SPropertyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_PROPERTY
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(SProperty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_PROPERTY
	 * @mbg.generated
	 */
	int updateByPrimaryKeyWithBLOBs(SProperty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_PROPERTY
	 * @mbg.generated
	 */
	int updateByPrimaryKey(SProperty record);
}