package com.lsheep.customer.database.model;

import java.math.BigDecimal;
import java.util.Date;

public class SPosition {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_POSITION.POSITION_ID
	 * @mbg.generated
	 */
	private Integer positionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_POSITION.OPERATE_IP
	 * @mbg.generated
	 */
	private String operateIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_POSITION.AUTHORIZE
	 * @mbg.generated
	 */
	private Boolean authorize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_POSITION.MODULE
	 * @mbg.generated
	 */
	private String module;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_POSITION.TYPE
	 * @mbg.generated
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_POSITION.ADCODE
	 * @mbg.generated
	 */
	private String adcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_POSITION.LATITUDE
	 * @mbg.generated
	 */
	private BigDecimal latitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_POSITION.LONGITUDE
	 * @mbg.generated
	 */
	private BigDecimal longitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_POSITION.ACCURACY
	 * @mbg.generated
	 */
	private Integer accuracy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_POSITION.CREATE_USER
	 * @mbg.generated
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_POSITION.CREATE_DATE
	 * @mbg.generated
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_POSITION.MODIFY_USER
	 * @mbg.generated
	 */
	private String modifyUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_POSITION.MODIFY_DATE
	 * @mbg.generated
	 */
	private Date modifyDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column S_POSITION.DELETED
	 * @mbg.generated
	 */
	private Boolean deleted;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_POSITION.POSITION_ID
	 * @return  the value of S_POSITION.POSITION_ID
	 * @mbg.generated
	 */
	public Integer getPositionId() {
		return positionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_POSITION.POSITION_ID
	 * @param positionId  the value for S_POSITION.POSITION_ID
	 * @mbg.generated
	 */
	public void setPositionId(Integer positionId) {
		this.positionId = positionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_POSITION.OPERATE_IP
	 * @return  the value of S_POSITION.OPERATE_IP
	 * @mbg.generated
	 */
	public String getOperateIp() {
		return operateIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_POSITION.OPERATE_IP
	 * @param operateIp  the value for S_POSITION.OPERATE_IP
	 * @mbg.generated
	 */
	public void setOperateIp(String operateIp) {
		this.operateIp = operateIp == null ? null : operateIp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_POSITION.AUTHORIZE
	 * @return  the value of S_POSITION.AUTHORIZE
	 * @mbg.generated
	 */
	public Boolean getAuthorize() {
		return authorize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_POSITION.AUTHORIZE
	 * @param authorize  the value for S_POSITION.AUTHORIZE
	 * @mbg.generated
	 */
	public void setAuthorize(Boolean authorize) {
		this.authorize = authorize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_POSITION.MODULE
	 * @return  the value of S_POSITION.MODULE
	 * @mbg.generated
	 */
	public String getModule() {
		return module;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_POSITION.MODULE
	 * @param module  the value for S_POSITION.MODULE
	 * @mbg.generated
	 */
	public void setModule(String module) {
		this.module = module == null ? null : module.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_POSITION.TYPE
	 * @return  the value of S_POSITION.TYPE
	 * @mbg.generated
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_POSITION.TYPE
	 * @param type  the value for S_POSITION.TYPE
	 * @mbg.generated
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_POSITION.ADCODE
	 * @return  the value of S_POSITION.ADCODE
	 * @mbg.generated
	 */
	public String getAdcode() {
		return adcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_POSITION.ADCODE
	 * @param adcode  the value for S_POSITION.ADCODE
	 * @mbg.generated
	 */
	public void setAdcode(String adcode) {
		this.adcode = adcode == null ? null : adcode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_POSITION.LATITUDE
	 * @return  the value of S_POSITION.LATITUDE
	 * @mbg.generated
	 */
	public BigDecimal getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_POSITION.LATITUDE
	 * @param latitude  the value for S_POSITION.LATITUDE
	 * @mbg.generated
	 */
	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_POSITION.LONGITUDE
	 * @return  the value of S_POSITION.LONGITUDE
	 * @mbg.generated
	 */
	public BigDecimal getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_POSITION.LONGITUDE
	 * @param longitude  the value for S_POSITION.LONGITUDE
	 * @mbg.generated
	 */
	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_POSITION.ACCURACY
	 * @return  the value of S_POSITION.ACCURACY
	 * @mbg.generated
	 */
	public Integer getAccuracy() {
		return accuracy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_POSITION.ACCURACY
	 * @param accuracy  the value for S_POSITION.ACCURACY
	 * @mbg.generated
	 */
	public void setAccuracy(Integer accuracy) {
		this.accuracy = accuracy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_POSITION.CREATE_USER
	 * @return  the value of S_POSITION.CREATE_USER
	 * @mbg.generated
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_POSITION.CREATE_USER
	 * @param createUser  the value for S_POSITION.CREATE_USER
	 * @mbg.generated
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser == null ? null : createUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_POSITION.CREATE_DATE
	 * @return  the value of S_POSITION.CREATE_DATE
	 * @mbg.generated
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_POSITION.CREATE_DATE
	 * @param createDate  the value for S_POSITION.CREATE_DATE
	 * @mbg.generated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_POSITION.MODIFY_USER
	 * @return  the value of S_POSITION.MODIFY_USER
	 * @mbg.generated
	 */
	public String getModifyUser() {
		return modifyUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_POSITION.MODIFY_USER
	 * @param modifyUser  the value for S_POSITION.MODIFY_USER
	 * @mbg.generated
	 */
	public void setModifyUser(String modifyUser) {
		this.modifyUser = modifyUser == null ? null : modifyUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_POSITION.MODIFY_DATE
	 * @return  the value of S_POSITION.MODIFY_DATE
	 * @mbg.generated
	 */
	public Date getModifyDate() {
		return modifyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_POSITION.MODIFY_DATE
	 * @param modifyDate  the value for S_POSITION.MODIFY_DATE
	 * @mbg.generated
	 */
	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column S_POSITION.DELETED
	 * @return  the value of S_POSITION.DELETED
	 * @mbg.generated
	 */
	public Boolean getDeleted() {
		return deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column S_POSITION.DELETED
	 * @param deleted  the value for S_POSITION.DELETED
	 * @mbg.generated
	 */
	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}
}