package com.lsheep.customer.database.mapper;

import com.lsheep.customer.database.model.SPosition;
import com.lsheep.customer.database.model.SPositionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SPositionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_POSITION
	 * @mbg.generated
	 */
	long countByExample(SPositionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_POSITION
	 * @mbg.generated
	 */
	int deleteByExample(SPositionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_POSITION
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer positionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_POSITION
	 * @mbg.generated
	 */
	int insert(SPosition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_POSITION
	 * @mbg.generated
	 */
	int insertSelective(SPosition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_POSITION
	 * @mbg.generated
	 */
	List<SPosition> selectByExample(SPositionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_POSITION
	 * @mbg.generated
	 */
	SPosition selectByPrimaryKey(Integer positionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_POSITION
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") SPosition record, @Param("example") SPositionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_POSITION
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") SPosition record, @Param("example") SPositionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_POSITION
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(SPosition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S_POSITION
	 * @mbg.generated
	 */
	int updateByPrimaryKey(SPosition record);
}